### ISSUE TITLE
Player doesn't move forward when changing its rotation

### ISSUE THREAD

**Issue by LuigiElleBalotta** [LuigiElleBalotta/ElleRealTime#3]
When changing player's rotation via "A" and "D" buttons this happens:
- The localPlayer moves, but the remote player doesn't see the rotation change even if sending "MoveAsync" (FIXED)
- When pressing "W" to walk after the rotation, the player doesn't go forward but goes straight using old rotation/facing
- When pressing for example W + A, the character plays Walk animation (it's ok), rotates (it's ok) but doesn't go forward.
- When not controlling the camera, it set its position to the left of the player and not to player's back

**Comment by LuigiElleBalotta** [comment]
Fix for the first point: https://github.com/LuigiElleBalotta/ElleRealTime/commit/c414ce713c0a1b6978d4234b76831ff6103443e6

**Comment by Reinisch** [comment]
2. You are not using unit direction when moving forward, do transform direction [there](https://github.com/LuigiElleBalotta/ElleRealTime/blob/master/MagicOnionTest/Assets/Scripts/Game/Entities/Unit/BaseUnit.cs#L74): like this:
```
transform.position += transform.TransformDirection(Vector3.forward * (m_Running ? speedRun : speedWalk) * Time.deltaTime);
```

**Comment by Reinisch** [comment]
4. Character rig is just rotated 90 degrees to the left, just add 90 to Y rotation to ladyalexstrasa_rig

**Comment by Reinisch** [comment]
3. You update only single input key and ignore all others if one is pressed, just handle rotation and movement separately or just remove __else__ from [here](https://github.com/LuigiElleBalotta/ElleRealTime/blob/master/MagicOnionTest/Assets/Scripts/Game/Entities/Unit/BaseUnit.cs#L72)

**Comment by LuigiElleBalotta** [comment]
3. Or handle double inputs before the single ones.. I'll check tomorrow
